/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testeoHorarios;

import entidades.Medico;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Jose Alejandro
 */
public class PruebaHora extends javax.swing.JFrame {

    /**
     * Creates new form PruebaHora
     */
    public PruebaHora() {
        initComponents();
    }
DAO d= new DAO();
String codhor="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbEspecial = new javax.swing.JComboBox<>();
        cbDoc = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        taHor = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cbEspecial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Seleccionar-", "Medicina General", "Obstetricia", "Odontologia", "Oftolmologia" }));
        cbEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEspecialActionPerformed(evt);
            }
        });

        cbDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Selecciona-" }));
        cbDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDocActionPerformed(evt);
            }
        });

        taHor.setColumns(20);
        taHor.setRows(5);
        jScrollPane2.setViewportView(taHor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbEspecial, 0, 143, Short.MAX_VALUE)
                            .addComponent(cbDoc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(cbEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(cbDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        List<String> lis=new ArrayList<>();
        List<String> lis2=new ArrayList<>();
    private void cbEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEspecialActionPerformed
        String tipo="";
            String cEsp="";
            tipo=cbEspecial.getSelectedItem().toString();
            if(tipo.equals("Medicina General")) cEsp="E01";
            if(tipo.equals("Obstetricia")) cEsp="E02";
            if(tipo.equals("Odontologia")) cEsp="E03";
            if(tipo.equals("Oftolmologia")) cEsp="E04";
            cbDoc.removeAllItems();
            cbDoc.addItem("-Seleccionar-");
            List<Medico> listaM=d.lisMedEs(cEsp);
            lis.clear();
            int max=listaM.size();
            for (int i = 0; i < max ; i++) {
                cbDoc.addItem(d.lisMedEs(cEsp).get(i).getNombre());
                lis.add(d.lisMedEs(cEsp).get(i).getIdhorario());
            }
            lis2=lis;
            //JOptionPane.showMessageDialog(null, lis.get(0).toString());
    }//GEN-LAST:event_cbEspecialActionPerformed

    private void cbDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDocActionPerformed
        int n= cbDoc.getSelectedIndex();
        //codhor= lis.get(n);
        JOptionPane.showMessageDialog(null, lis2.get(0));
    }//GEN-LAST:event_cbDocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaHora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaHora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDoc;
    private javax.swing.JComboBox<String> cbEspecial;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea taHor;
    // End of variables declaration//GEN-END:variables
}
